name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python Version
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --deploy --dev
    - name: Activate Virtual Enviornment
      run: pipenv shell
        
    - name: Collect static
      run: python manage.py collectstatic

    - name: Run tests
      run: python manage.py test
